version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

submodules:
  include: all
  recursive: true

python:
  install:
    - requirements: docs/requirements-doc.txt

sphinx:
  fail_on_warning: false
  configuration: docs/conf.py
